#define yy_create_buffer template_create_buffer
#define yy_delete_buffer template_delete_buffer
#define yy_scan_buffer template_scan_buffer
#define yy_scan_string template_scan_string
#define yy_scan_bytes template_scan_bytes
#define yy_flex_debug template_flex_debug
#define yy_init_buffer template_init_buffer
#define yy_flush_buffer template_flush_buffer
#define yy_load_buffer_state template_load_buffer_state
#define yy_switch_to_buffer template_switch_to_buffer
#define yyin templatein
#define yyleng templateleng
#define yylex templatelex
#define yyout templateout
#define yyrestart templaterestart
#define yytext templatetext

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /cvs/root/flex/flex/skel.c,v 1.2 2004/05/07 00:28:17 jkh Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 80
#define YY_END_OF_BUFFER 81
static yyconst short int yy_accept[287] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   81,   63,   61,   62,   80,    1,
       15,   11,   80,   13,   80,   80,   80,   26,   27,   35,
       33,   34,   56,   57,   58,   24,   24,   24,   32,   80,
       59,   60,   30,   31,   80,   39,   38,   80,   47,   46,
       48,   44,   80,   41,   80,   49,   61,   80,   80,   80,
       80,   80,   64,   54,   80,   66,   80,   18,   24,   19,
       80,   20,   80,   80,   80,   80,   80,   28,   80,   72,

       29,   71,   77,   78,   75,   63,   61,    0,    2,   15,
        0,   16,   12,   14,    0,    0,   26,   27,   35,   33,
       34,   56,   57,   58,   55,   26,   35,   33,   34,   56,
       57,   58,    0,   24,   24,   24,   32,    0,   59,   60,
       30,   31,    0,   38,    0,   40,   38,   36,   47,   43,
       45,    0,    0,   42,   37,   61,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   64,    0,   65,   67,    0,
       18,   19,   24,   19,    0,   20,   20,    0,   21,    0,
        0,    0,   28,    0,    0,   29,   71,   73,   71,   77,
       74,   76,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   55,   25,   23,   22,    0,    0,   53,    0,   50,
        0,   51,    0,   52,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   25,    0,    0,    0,
       79,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    7,   79,   79,    3,    5,
        0,    6,    9,    4,    8,    0,    0,   17,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   68,   69,
        0,   10,    0,    0,   70,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    1,    1,    8,
        9,    1,    1,   10,   11,    1,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,   15,
       16,   17,    1,   18,   19,   20,   21,   22,   23,   24,
       25,   19,   26,   19,   19,   27,   28,   29,   30,   31,
       19,   32,   33,   34,   19,   19,   19,   19,   19,   19,
        1,   35,    1,    1,   36,    1,   19,   20,   21,   22,

       37,   24,   38,   19,   26,   19,   19,   27,   39,   40,
       30,   31,   19,   32,   33,   34,   19,   19,   19,   41,
       19,   19,   42,    1,   43,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[44] =
    {   0,
        1,    1,    2,    1,    3,    1,    4,    1,    1,    1,
        1,    1,    5,    1,    1,    1,    1,    1,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    7,    1,    6,    6,    6,    6,
        6,    1,    1
    } ;

static yyconst short int yy_base[301] =
    {   0,
        0,    2,    3,    7,    0,    0,   42,    0,   84,   85,
       90,   94,  100,  103,  105,  107,  108,  111,  149,  177,
        6,  114,  206,    0,  118,  120,   12,   15,   23,  116,
      162,  180,   96,   97,  682,    0,  679,  683,  673,  672,
        0,  683,   13,  124,  683,  248,  662,  675,  683,  674,
      673,  672,  671,  670,  669,  657,  131,  126,  667,  189,
      652,  683,  683,  665,  143,  661,  663,  650,    0,  683,
      683,  152,  249,  658,  648,  683,  659,  653,   24,  167,
      188,  251,    0,  683,  652,  168,  252,  683,    0,  656,
       26,  655,   31,  264,  649,  267,  648,  683,  269,  649,

      683,  651,    0,  683,  250,    0,  650,  275,  683,    0,
       95,  683,  683,  683,    0,  635,  648,  683,  647,  646,
      645,  644,  643,  642,  641,  640,  639,  638,  637,  636,
      635,  634,  248,  619,  261,  266,  623,    0,  604,  683,
      683,  617,  278,  611,  598,  683,  603,  683,    0,  683,
      683,  288,  590,  683,  683,  598,  578,  268,  194,  289,
      299,  300,  306,  307,  310,    0,  289,  683,  683,  308,
      683,  550,    0,  549,  316,  548,  547,  138,  683,  325,
        0,  327,  683,  515,  330,  683,  545,  683,  544,    0,
      683,  683,  538,  323,  174,  318,  135,  313,  312,  330,

      333,  542,  531,  529,  528,  514,  341,  683,  346,  683,
      352,  683,  356,  683,  345,  340,  532,  346,  352,  151,
      357,  353,  358,  361,  360,  364,  526,  517,  365,  369,
      683,  529,  528,  527,  526,  525,  362,  524,  523,  522,
      521,  366,  370,  516,  514,  506,  505,  483,  406,  482,
      460,  459,  396,  431,  383,  683,  393,  391,  683,  683,
      454,  683,  683,  683,  683,  477,  512,  381,   27,  372,
      371,  393,  379,  286,  140,  513,  515,  392,  683,  683,
      185,  683,   20,  274,  683,  683,  554,  561,  568,  575,
      582,  589,  596,  602,  604,  610,  616,   12,  622,  628

    } ;

static yyconst short int yy_def[301] =
    {   0,
      287,  287,  288,  288,  289,  289,  286,    7,    7,    7,
      289,  289,  290,  290,  289,  289,  290,  290,  289,  289,
      291,  291,  286,   23,   23,   23,  289,  289,  289,  289,
      289,  289,  292,  292,  286,  293,  293,  286,  286,  286,
      294,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  295,  295,  295,  286,   46,
      286,  286,  286,  286,  286,  286,  286,  286,  296,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  297,  286,  286,  286,  286,  286,  298,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,

      286,  286,  299,  286,  286,  293,  293,  300,  286,  294,
      286,  286,  286,  286,   46,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  295,  295,  295,  286,   60,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  296,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  297,  300,  286,  286,  286,
      286,  286,  298,  286,  286,  286,  286,  286,  286,  286,
      300,  286,  286,  300,  286,  286,  286,  286,  286,  299,
      286,  286,  300,  300,  300,  300,  300,  300,  300,  300,

      300,  286,  286,  295,  295,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  300,  300,  286,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  286,  286,  300,  300,
      286,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      286,  300,  300,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  249,  300,  286,  286,  286,  286,  286,
      249,  286,  286,  286,  286,  249,  300,  286,  286,  300,
      300,  300,  286,  286,  286,  300,  300,  286,  286,  286,
      300,  286,  286,  300,  286,    0,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286

    } ;

static yyconst short int yy_nxt[727] =
    {   0,
      286,   37,   38,   37,   38,   42,   39,   43,   39,   42,
       84,   43,   85,   94,  111,  112,   94,  173,   95,   48,
       49,   95,   48,   49,   96,  158,  285,  175,  269,   97,
       48,   98,  178,  179,   40,  176,   40,   44,  273,  159,
       86,   44,   45,   46,   45,   47,   45,   45,   45,   48,
       49,   50,   45,   45,   51,   52,   53,   54,   55,   56,
       56,   56,   56,   57,   56,   56,   56,   58,   56,   56,
       56,   56,   56,   56,   56,   56,   45,   45,   56,   56,
       56,   56,   56,   59,   45,   60,   60,   61,   61,   62,
       62,   65,   63,   63,   66,   65,  111,  112,   66,   67,

      104,  104,   70,   67,   71,   70,   73,   71,   73,   74,
       70,   74,   76,   70,   67,   76,   67,   96,   84,   91,
       85,   91,   97,   48,   98,   64,   64,   92,  113,   92,
      105,  105,   68,   45,   72,   45,   68,   72,  133,  178,
      179,  217,   72,  133,  143,   72,  280,   75,   86,   75,
       77,   38,  144,  135,  136,   78,  150,  217,  114,   45,
       93,   45,   93,   99,  221,  136,  100,  135,  160,   48,
      101,   79,  168,   80,  234,  102,   81,   82,   77,   38,
      217,   99,  161,   78,  100,  145,  151,   48,  101,  162,
      138,  283,  139,  102,  140,  207,  284,  141,  208,   79,

      219,   80,  169,  163,   81,   82,   45,   87,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   88,   45,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       45,   45,   89,   89,   89,   89,   89,   90,   45,  115,
      152,  116,  164,  170,  191,  117,  118,  119,  144,  203,
      120,  121,  122,  123,  124,  180,  165,  171,  182,  158,
      185,  117,  118,  133,  117,  183,  117,  186,  133,  143,
      283,  204,  187,  159,  192,  284,  205,  144,  203,  152,
      160,  153,  279,  172,  194,  195,  196,  144,  197,  198,

      209,  162,  199,  210,  161,  200,  201,  211,  164,  170,
      212,  213,  198,  199,  214,  163,  215,  175,  217,  217,
      145,  216,  165,  171,  217,  176,  180,  215,  182,  217,
      153,  185,  117,  118,  117,  183,  217,  117,  186,  217,
      220,  223,  207,  187,  222,  208,  217,  209,  218,  172,
      210,  217,  217,  211,  220,  225,  212,  213,  217,  217,
      214,  224,  226,  217,  217,  232,  217,  217,  217,  225,
      217,  217,  217,  230,  229,  217,  217,  275,  274,  237,
      278,  239,  268,  236,  233,  238,  242,  240,  235,  217,
      273,  243,  269,  278,  268,  267,  282,  249,  238,  217,

      255,  254,  265,  276,  277,  243,  193,  193,  193,  193,
      193,  193,  217,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      193,  193,  261,  261,  261,  261,  261,  193,  193,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  264,  263,  266,  266,  266,
      266,  266,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  262,  260,
      270,  270,  270,  270,  270,  271,  271,  271,  271,  271,

      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  259,  258,  271,  271,  271,  271,  271,  217,  217,
      257,  217,  256,  272,  281,  276,  277,  253,  252,  251,
      250,  248,  247,  246,  245,  244,  241,  227,  231,  228,
      133,  133,  227,  202,  217,  189,  189,  216,  177,  177,
      174,  174,  272,  281,   36,   36,   36,   36,   36,   36,
       36,   41,   41,   41,   41,   41,   41,   41,   45,   45,
       45,   45,   45,   45,   45,   69,   69,   69,   69,   69,
       69,   69,   83,   83,   83,   83,   83,   83,   83,  103,
      103,  103,  103,  103,  103,  103,  106,  206,  106,  156,

      106,  106,  110,  155,  147,  110,  110,  110,  134,  134,
      149,  148,  147,  149,  149,  149,  166,  166,  142,  125,
      166,  166,  190,  190,  137,  190,  190,  190,  193,  193,
      193,  133,  193,  193,  193,  132,  131,  130,  129,  128,
      127,  126,  202,  132,  131,  130,  129,  128,  127,  126,
      125,  107,  189,  188,  184,  181,  177,  174,  167,  157,
      156,  155,  154,  148,  147,  146,  142,  125,  137,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  109,  108,
      107,  286,   35,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,

      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286
    } ;

static yyconst short int yy_chk[727] =
    {   0,
        0,    1,    1,    2,    2,    3,    1,    3,    2,    4,
       21,    4,   21,   27,   43,   43,   28,  298,   27,   27,
       27,   28,   28,   28,   29,   79,  283,   91,  269,   29,
       29,   29,   93,   93,    1,   91,    2,    3,  269,   79,
       21,    4,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    9,   10,    9,   10,    9,
       10,   11,    9,   10,   11,   12,  111,  111,   12,   11,

       33,   34,   13,   12,   13,   14,   15,   14,   16,   15,
       17,   16,   17,   18,   15,   18,   16,   30,   22,   25,
       22,   26,   30,   30,   30,    9,   10,   25,   44,   26,
       33,   34,   11,   25,   13,   26,   12,   14,   58,  178,
      178,  197,   17,   57,   65,   18,  275,   15,   22,   16,
       19,   19,   65,   57,   58,   19,   72,  220,   44,   25,
       25,   26,   26,   31,  197,   58,   31,   57,   80,   31,
       31,   19,   86,   19,  220,   31,   19,   19,   20,   20,
      195,   32,   80,   20,   32,   65,   72,   32,   32,   81,
       60,  281,   60,   32,   60,  159,  281,   60,  159,   20,

      195,   20,   86,   81,   20,   20,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   46,
       73,   46,   82,   87,  105,   46,   46,   46,   73,  133,
       46,   46,   46,   46,   46,   94,   82,   87,   96,  158,
       99,   94,   94,  135,   96,   96,   99,   99,  136,  143,
      284,  135,   99,  158,  105,  284,  136,  143,  133,  152,
      160,   73,  274,   87,  108,  108,  108,  152,  108,  108,

      161,  162,  108,  161,  160,  108,  108,  163,  164,  170,
      163,  165,  108,  108,  165,  162,  167,  175,  199,  198,
      143,  167,  164,  170,  196,  175,  180,  167,  182,  194,
      152,  185,  180,  180,  182,  182,  200,  185,  185,  201,
      196,  199,  207,  185,  198,  207,  216,  209,  194,  170,
      209,  215,  218,  211,  196,  201,  211,  213,  219,  222,
      213,  200,  201,  221,  223,  218,  225,  224,  237,  201,
      226,  229,  242,  216,  215,  230,  243,  271,  270,  223,
      273,  225,  268,  222,  219,  224,  229,  226,  221,  255,
      273,  230,  258,  278,  257,  255,  278,  237,  224,  272,

      243,  242,  253,  272,  272,  230,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  252,  251,  254,  254,  254,
      254,  254,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  250,  248,
      261,  261,  261,  261,  261,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  247,  246,  266,  266,  266,  266,  266,  267,  276,
      245,  277,  244,  267,  276,  277,  277,  241,  240,  239,
      238,  236,  235,  234,  233,  232,  228,  227,  217,  206,
      205,  204,  203,  202,  193,  189,  187,  184,  177,  176,
      174,  172,  267,  276,  287,  287,  287,  287,  287,  287,
      287,  288,  288,  288,  288,  288,  288,  288,  289,  289,
      289,  289,  289,  289,  289,  290,  290,  290,  290,  290,
      290,  290,  291,  291,  291,  291,  291,  291,  291,  292,
      292,  292,  292,  292,  292,  292,  293,  157,  293,  156,

      293,  293,  294,  153,  147,  294,  294,  294,  295,  295,
      296,  145,  144,  296,  296,  296,  297,  297,  142,  139,
      297,  297,  299,  299,  137,  299,  299,  299,  300,  300,
      300,  134,  300,  300,  300,  132,  131,  130,  129,  128,
      127,  126,  125,  124,  123,  122,  121,  120,  119,  117,
      116,  107,  102,  100,   97,   95,   92,   90,   85,   78,
       77,   75,   74,   68,   67,   66,   64,   61,   59,   56,
       55,   54,   53,   52,   51,   50,   48,   47,   40,   39,
       37,   35,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,

      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "template.l"
#define INITIAL 0
#line 2 "template.l"
#include <iostream>
#include "template.tab.h"
#include "template.h"
#include <string.h>

int nTemplateLine = 1;
bool bBib = false;
bool bMod = false;

#define DUPSTRING templatelval.string=strdup(templatetext)
#define DUPCHAR(c) templatelval.string=strdup(c)
#define DUPNUMBER(n) templatelval.number = n

/*
[\n]                        return NEWLINE;
[a-zA-Z][a-zA-Z0-9:.+/'\-]*  biblval.string=strdup(bibtext); return WORD;



*/
/*"*/
#define DEFINITION 1
#define HEAD 2
#define FOR 3
#define BIB 4
#define VALUES 5
#define VALUE 6
#define BIBVALUES 7
#define BIBVALUE 8
#define BIBTOKEN 9
#define BIBCONTENT 10
#define CLASS 11
#define MEMBERS 12
#define MOD 13
#define MODBIB 14
#define STEP 15
#define STEPCONTENT 16

#line 678 "lex.template.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 38 "template.l"


#line 832 "lex.template.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 287 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 683 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 40 "template.l"
{ DUPCHAR("\\"); return TOKEN_ALMOSTANY; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 41 "template.l"
{ DUPCHAR("%"); return TOKEN_ALMOSTANY; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "template.l"
{ BEGIN FOR; DUPSTRING; return TOKEN_FOR; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "template.l"
{ DUPSTRING; return TOKEN_ROF; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "template.l"
{ BEGIN FOR; DUPSTRING; return TOKEN_GRP; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "template.l"
{ DUPSTRING; return TOKEN_PRG; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 "template.l"
{ BEGIN BIB; DUPSTRING; return TOKEN_BIB; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 51 "template.l"
{ BEGIN INITIAL; DUPSTRING; return TOKEN_BIB; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 53 "template.l"
{ BEGIN FOR; return TOKEN_RED; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "template.l"
{ BEGIN DEFINITION; DUPSTRING; return TOKEN_DEF; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "template.l"
{ ++nTemplateLine; DUPCHAR("\n"); return TOKEN_DEFINITION; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 58 "template.l"
{ DUPCHAR("\""); return TOKEN_DEFINITION; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 59 "template.l"
{ DUPCHAR("\\"); return TOKEN_DEFINITION; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 60 "template.l"
{ DUPCHAR("\\"); return TOKEN_DEFINITION; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 61 "template.l"
{ /*"*/ DUPSTRING; return TOKEN_DEFINITION; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 62 "template.l"
{ ++nTemplateLine; BEGIN INITIAL; return TOKEN_FED; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 64 "template.l"
{ BEGIN CLASS; return TOKEN_CLASS; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 65 "template.l"
{ return TOKEN_EQUALS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 66 "template.l"
{ BEGIN MEMBERS; return TOKEN_LBRACE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 67 "template.l"
{ return TOKEN_COMMA; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 68 "template.l"
{ ++nTemplateLine; BEGIN INITIAL; return TOKEN_CLASS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 71 "template.l"
{ DUPSTRING; return TOKEN_SORT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 72 "template.l"
{ DUPSTRING; return TOKEN_SORT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 74 "template.l"
{ DUPSTRING; return TOKEN_WORD; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "template.l"
{ DUPSTRING; return TOKEN_WORDX; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 77 "template.l"
{ return TOKEN_LPAR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 78 "template.l"
{ BEGIN INITIAL; return TOKEN_RPAR; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 79 "template.l"
{ bMod = false; BEGIN BIBCONTENT; return TOKEN_RPAR; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 80 "template.l"
{ if ( bMod ) { BEGIN MODBIB; } else { BEGIN BIBCONTENT;} return TOKEN_RPAR; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 81 "template.l"
{ BEGIN BIBTOKEN; return TOKEN_RPAR; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 82 "template.l"
{ BEGIN BIBVALUES; return TOKEN_LBRACE;  }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 83 "template.l"
{ BEGIN VALUES; return TOKEN_LBRACE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 84 "template.l"
{ return TOKEN_COLON; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 85 "template.l"
{ return TOKEN_SEMICOLON; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 86 "template.l"
{ return TOKEN_COMMA; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 88 "template.l"
{ BEGIN FOR; return TOKEN_RBRACE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 89 "template.l"
{ BEGIN BIB; return TOKEN_RBRACE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 90 "template.l"
{ return TOKEN_COMMA; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 91 "template.l"
{ BEGIN VALUE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 92 "template.l"
{ DUPCHAR("\0"); return TOKEN_VALUE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 93 "template.l"
{ BEGIN BIBVALUE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 94 "template.l"
{ DUPCHAR("\0"); return TOKEN_VALUE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 95 "template.l"
{ DUPCHAR("\""); return TOKEN_VALUE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 96 "template.l"
{ DUPCHAR("\\"); return TOKEN_VALUE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 97 "template.l"
{ DUPCHAR("\\"); return TOKEN_VALUE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 98 "template.l"
{ ++nTemplateLine; DUPCHAR("\n"); return TOKEN_VALUE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 99 "template.l"
{ /*"*/ DUPSTRING; return TOKEN_VALUE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 100 "template.l"
{ BEGIN VALUES; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 101 "template.l"
{ BEGIN BIBVALUES;  }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 103 "template.l"
{ BEGIN BIBCONTENT; DUPNUMBER(bibtoken_generic);  return TOKEN_BIBTOKEN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 104 "template.l"
{ BEGIN BIBCONTENT; DUPNUMBER(bibtoken_missing);  return TOKEN_BIBTOKEN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 105 "template.l"
{ BEGIN BIBCONTENT; DUPNUMBER(bibtoken_nonempty); return TOKEN_BIBTOKEN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 106 "template.l"
{ BEGIN BIBCONTENT; DUPNUMBER(bibtoken_empty);    return TOKEN_BIBTOKEN; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 107 "template.l"
{ BEGIN BIBTOKEN; return TOKEN_BIBTOKENFINISHED; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 109 "template.l"
{ DUPSTRING; return TOKEN_OPERATOR; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 110 "template.l"
{ DUPSTRING; return TOKEN_OPERATOR; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 111 "template.l"
{ DUPSTRING; return TOKEN_OPERATOR; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 112 "template.l"
{ DUPSTRING; return TOKEN_OPERATOR; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 113 "template.l"
{ DUPSTRING; return TOKEN_EXCLAM;  }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 114 "template.l"
{ DUPSTRING; return TOKEN_HASH;  }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 117 "template.l"
{ DUPNUMBER(strlen(templatetext)); DUPSTRING; return TOKEN_WHITESPACE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 118 "template.l"
{ ++nTemplateLine; return TOKEN_NEWLINE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 119 "template.l"
{ DUPSTRING; return TOKEN_ALMOSTANY; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 120 "template.l"
{ /*"*/ DUPSTRING; return TOKEN_ALMOSTANY; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 121 "template.l"
{ DUPCHAR("\""); return TOKEN_ALMOSTANY; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 122 "template.l"
{ DUPCHAR("\\"); return TOKEN_ALMOSTANY; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 123 "template.l"
{ DUPCHAR("\\"); return TOKEN_ALMOSTANY; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 126 "template.l"
{ BEGIN MOD; DUPSTRING; return TOKEN_MOD; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 127 "template.l"
{ bMod = true; BEGIN MODBIB; DUPSTRING; return TOKEN_MOD; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 128 "template.l"
{ BEGIN STEP; DUPSTRING; return TOKEN_STEP; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 129 "template.l"
{ return TOKEN_SEMICOLON; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 130 "template.l"
{ BEGIN STEPCONTENT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 131 "template.l"
{ return TOKEN_STEPCONTENT; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 132 "template.l"
{ DUPCHAR("\""); return TOKEN_STEPCONTENT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 133 "template.l"
{ DUPCHAR("\\"); return TOKEN_STEPCONTENT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 134 "template.l"
{ DUPCHAR("\\"); return TOKEN_STEPCONTENT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 135 "template.l"
{ /*"*/ DUPSTRING; return TOKEN_STEPCONTENT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 136 "template.l"
{ BEGIN STEP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 137 "template.l"
{ DUPSTRING; return TOKEN_COMMAND; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 141 "template.l"
ECHO;
	YY_BREAK
#line 1315 "lex.template.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DEFINITION):
case YY_STATE_EOF(HEAD):
case YY_STATE_EOF(FOR):
case YY_STATE_EOF(BIB):
case YY_STATE_EOF(VALUES):
case YY_STATE_EOF(VALUE):
case YY_STATE_EOF(BIBVALUES):
case YY_STATE_EOF(BIBVALUE):
case YY_STATE_EOF(BIBTOKEN):
case YY_STATE_EOF(BIBCONTENT):
case YY_STATE_EOF(CLASS):
case YY_STATE_EOF(MEMBERS):
case YY_STATE_EOF(MOD):
case YY_STATE_EOF(MODBIB):
case YY_STATE_EOF(STEP):
case YY_STATE_EOF(STEPCONTENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 287 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 287 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 286);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 141 "template.l"
